services:
  backend:
    build:
      context: ./backend/MiniLab/
      dockerfile: ./Dockerfile
    env_file: "./backend/MiniLab/target/env"

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile.dev
      # dockerfile: ./Dockerfile
    environment:
      BACKEND_URL: backend:8080
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./frontend:/frontend
