server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    url: ${minilab.datasource.driver-class-name}
    username: ${minilab.datasource.username}
    password: ${minilab.datasource.password}


#mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: DEBUG
    com:
      minilab:
        mapper: debug
        service: info
        controller: info

minilab:
  jwt:
    admin-secret-key: MiniLab
    admin-ttl: 7200000000
    admin-token-name: token