server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306
    username: ${DB_USER}
    password: ${DB_PASS}
  application:
    name: minilab-backend
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          prefer-ip: true


#mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: DEBUG
    com:
      minilab:
        mapper: debug
        service: info
        controller: info

minilab:
  jwt:
    admin-secret-key: MiniLab
    admin-ttl: 7200000000
    admin-token-name: token

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0  # 100% 追蹤（正式環境建議 <1.0）
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always
